#theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: My Portfolio
description: About Me
            I am an experienced Data Analyst with a strong background in transforming complex data into actionable insights that drive product improvement and business success. 

            I am passionate about leveraging data to create impactful solutions, collaborating with cross-functional teams, and driving data-driven decisions.

            I am expanding my technical capabilities by learning machine learning algorithms to further my contribution to advanced analytics and predictive modelling. 

            TechStack- SQL, Python
            
            My portfolio showcases a selection of my projects, reflecting my dedication to delivering high-quality, data-driven insights.

links:
  - title: "Home"
    url: "/https://github.com/dhadwalranjana/PortfolioProjectsPart1/blob/main/README.md"
  - title: "Covid Data Exploration"
    url: "https://github.com/dhadwalranjana/PortfolioProjectsPart1/blob/main/Covid%20Portfolio%20Project%20script.sql"
  - title: "Nashville Housing Data Cleaning"
    url: "https://github.com/dhadwalranjana/PortfolioProjectsPart1/blob/main/Data%20Cleaning%20for%20Nashville%20Housing%20dataset.sql"
